"""adaptive rate limiting

Revision ID: 7a2be2aa2bb0
Revises: 0dbe5d36e4b0
Create Date: 2026-09-18 15:49:58.186457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7a2be2aa2bb0"
down_revision: Union[str, None] = "0dbe5d36e4b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing batches need a default for the two new NOT NULL columns;
    # both match the model's Python-level default of True.
    op.add_column(
        "batches",
        sa.Column(
            "allow_concurrency", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "adaptive_rate_limiting",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        "batches",
        sa.Column("last_rate_limit_hit_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "batches",
        sa.Column("last_rate_recovery_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "batches",
        "max_tasks_per_minute",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_column("batches", "max_parallel_tasks")
    op.add_column("llm_requests", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_requests", "error")
    op.add_column(
        "batches",
        sa.Column(
            "max_parallel_tasks",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            server_default="1",
        ),
    )
    op.alter_column(
        "batches",
        "max_tasks_per_minute",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("batches", "last_rate_recovery_at")
    op.drop_column("batches", "last_rate_limit_hit_at")
    op.drop_column("batches", "adaptive_rate_limiting")
    op.drop_column("batches", "allow_concurrency")
    # ### end Alembic commands ###
